//
// Created by valentin.ackva on 25.10.2023.
//

#ifndef NN_INFERENCE_TEMPLATE_CONFIG_H
#define NN_INFERENCE_TEMPLATE_CONFIG_H

#define DEFAULT_EDITOR_WIDTH 520
#define DEFAULT_EDITOR_HEIGHT 750

#endif //NN_INFERENCE_TEMPLATE_CONFIG_H
